name: build-rp2040
on:
  push:
    paths:
      - 'firmware/**'
  workflow_call:
defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install compiler, libraries and tools
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib srecord
      - name: Build Single Pico Version Only
        run: |
          mkdir build
          cd build
          cmake ..
          make remapper
          cd ..
          mkdir artifacts
          mv build/remapper.uf2 artifacts/remapper_custom.uf2
          ls -la artifacts/
        working-directory: ./firmware
      - uses: actions/upload-artifact@v4
        with:
          name: hid-remapper-custom-firmware
          path: firmware/artifacts/*
