name: build-rp2040
on:
  push:
    paths:
      - 'firmware/**'
  workflow_call:
defaults:
  run:
    shell: bash --noprofile --norc -x -e -o pipefail {0}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install compiler, libraries and tools
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib srecord
      - name: Build
        run: |
          # 只编译核心版本，大幅减少编译时间
          mkdir build
          cd build
          cmake ..
          make remapper
          cd ..

          # 如果需要其他板子，可以取消注释相应部分
          # mkdir build-pico2
          # cd build-pico2
          # PICO_BOARD=pico2 cmake ..
          # make remapper
          # cd ..

          mkdir artifacts
          mv build/remapper.uf2 artifacts/
          # mv build-pico2/remapper.uf2 artifacts/remapper_pico2.uf2
        working-directory: ./firmware
      - uses: actions/upload-artifact@v4
        with:
          path: firmware/artifacts/*
